services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: https://github.com/Seazer-x/alist-render.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        value: satao.db.elephantsql.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: lqqqtgwx
      - key: DB_PASS
        value: BlzIVsACIGC1-_8uTSX5hWjl50759el5
      - key: DB_NAME
        value: lqqqtgwx
      - key: DB_SSL_MODE
        value: disable
        
