services:
  # A Docker web service
  - type: web
    name: myalist
    env: docker
    repo: https://github.com/SurpassHR/alist-render.git
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        value: satao.db.elephantsql.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: gjconxhi
      - key: DB_PASS
        value: VL7e1YalQioLWKZFt3C2hzMC11m_woTq
      - key: DB_NAME
        value: alist-render
      - key: DB_SSL_MODE
        value: disable
        
