services:
  # A Docker web service
  - type: web
    name: myalist
    env: docker
    repo: https://github.com/Seazer-x/alist-render.git
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        value: satao.db.elephantsql.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: quhszxme
      - key: DB_PASS
        value: w43ZPnNn9TciaLopt-u1G7oN_ob4G_Sq
      - key: DB_NAME
        value: quhszxme
      - key: DB_SSL_MODE
        value: disable
        
